version: "3"
services:
  web:
    build: .
    working_dir: /app
    restart: on-failure
    stdin_open: true
    env_file:
      - .env
    tty: true
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"